### ISSUE TITLE
creation of the checklist

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#2187] opened 2015-04-13 15:26 UTC
[Originally posted on GoogleCode (id 910) on 2012-01-12 by maria.l.kuzmina]

Dear VASCAN team,

I questioned myself with the following task: to find the list of the species of the flowering plants (in your case, subclass Magnoliidae, I think) which appear inside Canada. I used all filter criteria on you site, and tried to create a checklist. It created some funny text file (attached) with the list of the provinces. Very disappointing...What do I do wrong?

Appreciate your help. 

Masha

mkuzmina@uoguelph.ca

**Comment by brouille** [comment] 2015-04-13 15:26
[Originally posted on GoogleCode on 2012-01-13 13:32Z by luc.brouillet]

Dear Masha

I forwarded your message to Peter Desmet, who is better able to answer you.

**Comment by peterdesmet** [comment] 2015-04-14 12:13
[Originally posted on GoogleCode on 2012-01-17 17:45Z]

Thanks for reporting. I'll try to repeat the issue today. More info coming soon.

**Comment by brouille** [comment] 2015-04-14 13:07
[Originally posted on GoogleCode on 2012-01-17 18:37Z by maria.l.kuzmina]

Dear Peter,

I think I already sorted things out, so you can skip my request. The problem was that I misunderstood the filtering criteria based on taxonomy. It seems your system is based on sorting the names, not strongly ranked taxa. E.g., when you select Magnoliopsidae, it does not give you the list of all species from this subclass. It does not work like this. It searches only this name. Is it correct?
But I managed to get the full list of all taxa, and then sorted them in excel.

Thank you very much. Very useful site!

Masha

**Comment by cgendreau** [comment] 2015-04-14 13:08
[Originally posted on GoogleCode on 2012-01-17 18:41Z]

Peter, I tried "all Magnoliidae in Canada" :
http://data.canadensys.net/vascan/checklist?lang=en&habit=all&taxon=8&combination=anyof&province=BC&province=AB&province=SK&province=MB&province=ON&province=QC&province=NB&province=PE&province=NS&province=NL_N&province=NL_L&province=YT&province=NT&province=NU&status=native&status=introduced&status=ephemeral&status=excluded&status=extirpated&status=doubtful&rank=class&rank=subclass&rank=superorder&rank=order&rank=family&rank=subfamily&rank=tribe&rank=subtribe&rank=genus&rank=subgenus&rank=section&rank=subsection&rank=series&rank=species&rank=subspecies&rank=variety&hybrids=true&nohybrids=false&limitResults=true&nolimit=false&sort=taxonomically

This query is working and the text file is fine.

**Comment by peterdesmet** [comment] 2015-04-14 13:09
[Originally posted on GoogleCode on 2012-01-19 23:40Z]

Dear Masha,

I'm happy you sorted things out and you were able to get the list.

I'm not sure exactly what went wrong. The link Christian provided is indeed the correct one to get all taxa from the subclass Magnoliidae in Canada (9426 results). So, if you select "Magnoliidae" in the checklist builder, it considers "Magnoliidae" as a group, not a name, and will search for all taxa (including species) from that group (hence the 9426 results).
You can combine 4 kinds of criteria in the checklist builder: group (taxon), habit, distribution (provinces) + how to combine them and distribution status. Generally, the more criteria you combine, the more restrictive the search. The display criteria do not alter the initial search, but allow you to only return certain ranks (e.g. species only) and customize your list.

Hope this helps for future queries.

**Comment by cgendreau** [comment] 2015-04-14 13:09
[Originally posted on GoogleCode on 2012-01-26 15:40Z]

In fact, the initial criteria could not be transferred into valid request. This should not happen but I'm not able to reproduce the issue.
Here is the stacktrace for future reference if needed:

com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')
AND  (lookup.rank = 'class' OR lookup.rank = 'subclass' OR lookup.rank = 'supe'
at net.canadensys.dataportal.vascan.LookupManager.getDistributions(LookupManager.java:76)
This query is indeed not valid but, the LookupManager cannot create a query like this. Since I cannot reproduce the bug, I'll leave the issue status to "Done"

**Closed** 2015-04-14 13:10 UTC
